// Copyright 2015 by Paulo Augusto Peccin. See license.txt distributed with this file.

jt.PeripheralControls = {

    SCREEN_ASPECT_PLUS: 1, SCREEN_ASPECT_MINUS: 2,
    SCREEN_SCALE_PLUS: 3, SCREEN_SCALE_MINUS: 4,
    VIEWPORT_ORIGIN_PLUS: 5, VIEWPORT_ORIGIN_MINUS: 6,
    VIEWPORT_SIZE_PLUS: 7, VIEWPORT_SIZE_MINUS: 8,

    SCREEN_FULLSCREEN: 10,
    SCREEN_CRT_FILTER: 11, SCREEN_CRT_MODE: 12,
    SCREEN_TOGGLE_MENU: 13,
    SCREEN_OPEN_HELP: 14,
    SCREEN_OPEN_ABOUT: 15,
    SCREEN_OPEN_SETTINGS: 16,
    SCREEN_OPEN_QUICK_OPTIONS: 17,
    SCREEN_DEFAULTS: 18,

    SCREEN_CONSOLE_PANEL_TOGGLE: 19,

    SPEAKER_BUFFER_TOGGLE: 20,

    CONSOLE_POWER_TOGGLE: 102, CONSOLE_POWER_FRY: 103,
    CONSOLE_LOAD_STATE_FILE: 104, CONSOLE_SAVE_STATE_FILE: 105, CONSOLE_LOAD_STATE_MENU: 106, CONSOLE_SAVE_STATE_MENU: 107,

    P1_CONTROLS_TOGGLE: 201, JOYSTICKS_TOGGLE_MODE: 202, PADDLES_TOGGLE_MODE: 203, TOUCH_TOGGLE_MODE: 204, TOUCH_TOGGLE_DIR_BIG: 205, TURBO_FIRE_TOGGLE: 206,
    HAPTIC_FEEDBACK_TOGGLE_MODE: 207,

    CAPTURE_SCREEN: 304,

    CARTRIDGE_LOAD_RECENT: 40,
    CARTRIDGE_LOAD_FILE: 41, CARTRIDGE_LOAD_URL: 42, CARTRIDGE_REMOVE: 43, CARTRIDGE_LOAD_DATA_FILE: 44, CARTRIDGE_SAVE_DATA_FILE: 45, CARTRIDGE_CHOOSE_FORMAT: 46,
    AUTO_LOAD_FILE: 46, AUTO_LOAD_URL: 47,

    SCREEN_OPEN_NETPLAY: 500

};
